/**
* @author Globant 
* @description Apex class Class3Example example
* @date 02-27-2021
* Version
* ---------------------------------------------------------------------------------------------------
* No.   Date        Author                  Description
* ---   -----       -------                 ---------------------------------------------------------
* 1.0   09-07-2022  Jeisson Hernandez(JH)   Class creation 
*/
public with sharing class Class3Example 
{
    /**
    * @description Constructor of the class 
    */
    public Class3Example() 
    {
        System.debug(LoggingLevel.ERROR, 'New Commit US-03');
    }
}
